---
on:
  pull_request:
  push:
    branches:
      - main

permissions: read-all

jobs:
  pre-commit:
    uses: "Mosher-Labs/.github/.github/workflows/pre-commit.yml@heimdallr"
  heimdallr:
    needs: pre-commit
    uses: "Mosher-Labs/.github/.github/workflows/heimdallr.yml@heimdallr"
    secrets: inherit
    with:
      slack_message: The project [${{ github.repositoryurl }}](${{ github.repository }}) just released version [#](v0.4.0).
