---
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: "Mosher-Labs/.github/.github/workflows/release.yml@v0.3.0"

  heimdallr:
    needs: release
    uses: "Mosher-Labs/.github/.github/workflows/heimdallr.yml@heimdallr"
    secrets: inherit
    with:
      slack_message: "The project $GITHUB_REPOSITORY just released version ${{ needs.release.outputs.next_version }}."
