---
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    uses: "Mosher-Labs/.github/.github/workflows/release.yml@main"
    permissions:
      contents: write
      # actions: read
      # attestations: read
      # checks: read
      # deployments: read
      # discussions: read
      # issues: read
      # packages: read
      # pages: read
      # pull-requests: read
      # repository-projects: read
      # statuses: read
      # security-events: read
      # id-token: read

  heimdallr:
    needs: release
    uses: "Mosher-Labs/.github/.github/workflows/heimdallr.yml@main"
    secrets: inherit
    with:
      slack_message: "The project <https://github.com/${{ github.repository }}|${{ github.repository }}> just released version <https://github.com/${{ github.repository }}/releases/tag/${{ needs.release.outputs.next_version }}|${{ needs.release.outputs.next_version }}>."
