---
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: "Mosher-Labs/.github/.github/workflows/release.yml@v0.3.0"

  heimdallr:
    uses: "Mosher-Labs/.github/.github/workflows/heimdallr.yml@heimdallr"
    secrets: inherit
    with:
      message: "Testing pre-commit slack messages."
