---
on:
  workflow_call:
    inputs:
      message:
        required: false
        type: string
        default: "Default slack message."

permissions: read-all

jobs:
  heimdallr:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Message
        uses: archive/github-actions-slack@v2.9.0
        id: send-message

        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{ secrets.SLACK_PLATFORM_NOTIFICATIONS_CHANNEL_ID }}
          slack-text: ${{ github.event.inputs.message }}

      - name: Send Slack Message Result
        run: echo "Data - ${{ steps.send-message.outputs.slack-result }}"
